name: youriotmanagerapp
description: A new Flutter project.

publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  what3words: 3.1.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  firebase_storage: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true