// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvw24VlkUEy7wz6jBi0SPqKT9c06Pdyns',
    appId: '1:467482761094:web:90f88fd9e76d3392467e07',
    messagingSenderId: '467482761094',
    projectId: 'your-iot-device-manager',
    authDomain: 'your-iot-device-manager.firebaseapp.com',
    storageBucket: 'your-iot-device-manager.appspot.com',
    measurementId: 'G-X9VZR64DB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATQaJTejVg_FTFn7IJ3-aFuOcC3GLq2s',
    appId: '1:467482761094:android:5cdd25fdbbd5c991467e07',
    messagingSenderId: '467482761094',
    projectId: 'your-iot-device-manager',
    storageBucket: 'your-iot-device-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzFic8DWr2MIj0fLB-RIbk4IAEL3_uYfo',
    appId: '1:467482761094:ios:895187c507606120467e07',
    messagingSenderId: '467482761094',
    projectId: 'your-iot-device-manager',
    storageBucket: 'your-iot-device-manager.appspot.com',
    iosClientId: '467482761094-7533h30648qtn8d6qi59b6qfs0h2l2nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.youriotdevicemanagerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzFic8DWr2MIj0fLB-RIbk4IAEL3_uYfo',
    appId: '1:467482761094:ios:895187c507606120467e07',
    messagingSenderId: '467482761094',
    projectId: 'your-iot-device-manager',
    storageBucket: 'your-iot-device-manager.appspot.com',
    iosClientId: '467482761094-7533h30648qtn8d6qi59b6qfs0h2l2nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.youriotdevicemanagerapp',
  );
}
